package com.autohr.modules.interview.service;

import com.autohr.modules.interview.dto.AiAnswerRequest;
import com.autohr.modules.interview.dto.AntiCheatEventRequest;
import com.autohr.modules.interview.dto.InterviewDecisionRequest;
import com.autohr.modules.interview.dto.InterviewVO;
import com.autohr.modules.interview.dto.JobKnowledgeWeightSaveRequest;
import com.autohr.modules.interview.dto.KnowledgeBaseSaveRequest;
import com.autohr.modules.interview.dto.KnowledgeItemSaveRequest;
import com.autohr.modules.interview.dto.LlmConfigSaveRequest;
import com.autohr.modules.interview.dto.StartInterviewProcessRequest;
import com.autohr.modules.interview.dto.VideoSignalRequest;
import com.autohr.modules.interview.dto.VideoSignalVO;
import com.autohr.modules.interview.entity.InterviewVideoSession;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

public interface InterviewService {
    InterviewVO saveKnowledgeBase(KnowledgeBaseSaveRequest request);
    List<InterviewVO> listKnowledgeBases(Integer status, String keyword);
    void deleteKnowledgeBase(Long id);
    InterviewVO saveKnowledgeItem(KnowledgeItemSaveRequest request);
    int importKnowledgeItems(Long knowledgeBaseId, MultipartFile file);
    List<InterviewVO> listKnowledgeItems(Long knowledgeBaseId, String keyword);
    void deleteKnowledgeItem(Long id);
    InterviewVO saveJobKnowledgeWeight(JobKnowledgeWeightSaveRequest request);
    List<InterviewVO> listJobKnowledgeWeights(Long jobId);
    void deleteJobKnowledgeWeight(Long id);
    InterviewVO saveLlmConfig(LlmConfigSaveRequest request);
    List<InterviewVO> listLlmConfigs(String modelRole, Integer status);
    void deleteLlmConfig(Long id);
    InterviewVO startInterviewProcess(StartInterviewProcessRequest request);
    List<InterviewVO> listProcesses(String overallStatus, String stageStatus, String keyword);
    InterviewVO getProcess(Long processId);
    InterviewVO getIntervieweeProcess(Long processId, Long intervieweeUserId);
    InterviewVO getNextAiQuestion(Long processId);
    InterviewVO getIntervieweeNextAiQuestion(Long processId, Long intervieweeUserId);
    InterviewVO submitAiAnswer(AiAnswerRequest request);
    InterviewVO submitIntervieweeAiAnswer(AiAnswerRequest request, Long intervieweeUserId);
    List<InterviewVO> listAiRecords(Long processId);
    List<InterviewVO> listIntervieweeAiRecords(Long processId, Long intervieweeUserId);
    InterviewVO createVideoSession(Long processId, Long approverUserId, String approverName);
    InterviewVO intervieweeJoinVideo(Long processId, Long intervieweeUserId, String intervieweeName);
    InterviewVO hrJoinVideo(Long processId, Long approverUserId, String approverName);
    InterviewVO completeVideoSession(Long processId, String recordingPath);
    InterviewVO requestIntervieweeVideoEnd(Long processId, Long intervieweeUserId);
    VideoSignalVO publishHrOffer(Long processId, VideoSignalRequest request);
    VideoSignalVO submitIntervieweeAnswer(Long processId, VideoSignalRequest request, Long intervieweeUserId, String intervieweeName);
    VideoSignalVO addHrIceCandidate(Long processId, VideoSignalRequest request);
    VideoSignalVO addIntervieweeIceCandidate(Long processId, VideoSignalRequest request, Long intervieweeUserId, String intervieweeName);
    VideoSignalVO getVideoSignalState(Long processId);
    VideoSignalVO uploadHrRecording(Long processId, String originalFileName, String contentType, MultipartFile file);
    VideoSignalVO uploadIntervieweeRecording(Long processId, Long intervieweeUserId, String intervieweeName, String originalFileName, String contentType, MultipartFile file);
    InterviewVO reportAntiCheatEvent(AntiCheatEventRequest request, Long intervieweeUserId, String intervieweeName);
    InterviewVideoSession getVideoSession(Long processId);
    InterviewVideoSession getDownloadableVideoSession(Long processId);
    InterviewVO approveAiToVideo(Long processId, InterviewDecisionRequest request);
    InterviewVO approveVideoToOnsite(Long processId, InterviewDecisionRequest request);
    InterviewVO decideOnsite(Long processId, InterviewDecisionRequest request);
    InterviewVO terminateProcess(Long processId, InterviewDecisionRequest request);
    InterviewVO updateProcessRemark(Long processId, InterviewDecisionRequest request);
}
