package com.autohr.config.database;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.List;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
@EnableConfigurationProperties(AppMigrationProperties.class)
public class DatabaseMigrationRunner implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseMigrationRunner.class);

    private final DataSource dataSource;
    private final ActiveDatabase activeDatabase;
    private final AppMigrationProperties properties;

    public DatabaseMigrationRunner(DataSource dataSource, ActiveDatabase activeDatabase, AppMigrationProperties properties) {
        this.dataSource = dataSource;
        this.activeDatabase = activeDatabase;
        this.properties = properties;
    }

    @Override
    public void run(String... args) throws Exception {
        if (!properties.isEnabled()) {
            log.info("Database migration disabled");
            return;
        }
        List<String> statements = loadStatements();
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                execute(statement, sql);
            }
            migrateInterviewProcessColumns(connection, statement);
        }
        log.info("Database migration completed for {}", activeDatabase.type());
    }

    private List<String> loadStatements() throws IOException {
        String schema = new ClassPathResource("schema.sql")
                .getContentAsString(StandardCharsets.UTF_8)
                .replace("\r\n", "\n");
        return Arrays.stream(toDialect(schema).split(";"))
                .map(String::trim)
                .filter(sql -> !sql.isEmpty())
                .toList();
    }

    private String toDialect(String schema) {
        return switch (activeDatabase.type()) {
            case SQLITE -> schema;
            case MYSQL -> schema
                    .replace("CREATE INDEX IF NOT EXISTS", "CREATE INDEX")
                    .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER PRIMARY KEY AUTO_INCREMENT");
            case PGSQL -> schema
                    .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                    .replace("DATETIME", "TIMESTAMP");
        };
    }

    private void execute(Statement statement, String sql) throws SQLException {
        try {
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            if (isIgnorable(sql, ex)) {
                log.debug("Skipping existing migration object: {}", firstLine(sql));
                return;
            }
            throw ex;
        }
    }

    private boolean isIgnorable(String sql, SQLException ex) {
        String normalized = sql.stripLeading().toUpperCase();
        if (normalized.startsWith("CREATE INDEX")) {
            String state = ex.getSQLState();
            int errorCode = ex.getErrorCode();
            return "42S11".equals(state)
                    || "42710".equals(state)
                    || errorCode == 1061
                    || messageContains(ex, "already exists")
                    || messageContains(ex, "Duplicate key name");
        }
        return false;
    }

    private void migrateInterviewProcessColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_process", "ai_max_question_rounds", "INTEGER NOT NULL DEFAULT 5");
        addColumnIfMissing(connection, statement, "interview_process", "ai_recording_path", varchar(500));
        addColumnIfMissing(connection, statement, "interview_process", "ai_recording_file_name", varchar(255));
    }

    private void addColumnIfMissing(Connection connection, Statement statement, String table, String column, String definition) throws SQLException {
        if (columnExists(connection, table, column)) {
            return;
        }
        execute(statement, "ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
        log.info("Added migration column {}.{}", table, column);
    }

    private boolean columnExists(Connection connection, String table, String column) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet columns = metaData.getColumns(null, null, table, column)) {
            if (columns.next()) {
                return true;
            }
        }
        try (ResultSet columns = metaData.getColumns(null, null, table.toUpperCase(), column.toUpperCase())) {
            return columns.next();
        }
    }

    private String varchar(int length) {
        return "VARCHAR(" + length + ")";
    }

    private boolean messageContains(SQLException ex, String value) {
        return ex.getMessage() != null && ex.getMessage().contains(value);
    }

    private String firstLine(String sql) {
        int index = sql.indexOf('\n');
        return index >= 0 ? sql.substring(0, index) : sql;
    }
}
