package com.autohr.config.database;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.List;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
@EnableConfigurationProperties(AppMigrationProperties.class)
public class DatabaseMigrationRunner implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseMigrationRunner.class);
    private static final List<String> PRIMARY_KEY_TABLES = List.of(
            "hr_department", "hr_employee", "hr_integration_binding",
            "recruitment_job", "recruitment_candidate", "recruitment_resume_file",
            "interview_batch", "interview_question", "interview_candidate", "interview_submission",
            "sys_user", "sys_audit_log",
            "interview_knowledge_base", "interview_knowledge_item", "interview_job_knowledge_weight",
            "interview_llm_config", "interview_process", "interview_ai_record", "interview_video_session",
            "interview_process_template", "interview_process_template_stage", "interview_process_stage"
    );

    private final DataSource dataSource;
    private final ActiveDatabase activeDatabase;
    private final AppMigrationProperties properties;

    public DatabaseMigrationRunner(DataSource dataSource, ActiveDatabase activeDatabase, AppMigrationProperties properties) {
        this.dataSource = dataSource;
        this.activeDatabase = activeDatabase;
        this.properties = properties;
    }

    @Override
    public void run(String... args) throws Exception {
        if (!properties.isEnabled()) {
            log.info("Database migration disabled");
            return;
        }
        List<String> statements = loadStatements();
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            for (String sql : statements.stream().filter(sql -> !isCreateIndex(sql)).toList()) {
                execute(statement, sql);
            }
            migrateInterviewProcessColumns(connection, statement);
            migrateInterviewProcessTemplateColumns(connection, statement);
            migrateInterviewAiRecordColumns(connection, statement);
            migrateInterviewVideoSessionColumns(connection, statement);
            migrateInterviewProcessStageColumns(connection, statement);
            migrateRecruitmentCandidateColumns(connection, statement);
            migrateRecruitmentJobColumns(connection, statement);
            migrateHrEmployeeColumns(connection, statement);
            migrateSysUserColumns(connection, statement);
            migrateReferentialIntegrityConstraints(connection, statement);
            assertNoDuplicateBusinessKeys(statement);
            migrateDatabaseGeneratedPrimaryKeys(connection, statement);
            for (String sql : statements.stream().filter(this::isCreateIndex).toList()) {
                execute(statement, sql);
            }
        }
        log.info("Database migration completed for {}", activeDatabase.type());
    }

    private List<String> loadStatements() throws IOException {
        String schema = new ClassPathResource("schema.sql")
                .getContentAsString(StandardCharsets.UTF_8)
                .replace("\r\n", "\n");
        return Arrays.stream(toDialect(schema).split(";"))
                .map(String::trim)
                .filter(sql -> !sql.isEmpty())
                .toList();
    }

    private String toDialect(String schema) {
        return switch (activeDatabase.type()) {
            case SQLITE -> schema;
            case MYSQL -> schema
                    .replace("CREATE UNIQUE INDEX IF NOT EXISTS", "CREATE UNIQUE INDEX")
                    .replace("CREATE INDEX IF NOT EXISTS", "CREATE INDEX")
                    .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER PRIMARY KEY AUTO_INCREMENT");
            case PGSQL -> schema
                    .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                    .replace("DATETIME", "TIMESTAMP");
        };
    }

    private void execute(Statement statement, String sql) throws SQLException {
        try {
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            if (isIgnorable(sql, ex)) {
                log.debug("Skipping existing migration object: {}", firstLine(sql));
                return;
            }
            throw ex;
        }
    }

    private boolean isIgnorable(String sql, SQLException ex) {
        String normalized = sql.stripLeading().toUpperCase();
        if (isCreateIndex(sql)) {
            String state = ex.getSQLState();
            int errorCode = ex.getErrorCode();
            return "42S11".equals(state)
                    || "42710".equals(state)
                    || errorCode == 1061
                    || messageContains(ex, "already exists")
                    || messageContains(ex, "Duplicate key name");
        }
        return false;
    }

    private boolean isCreateIndex(String sql) {
        String normalized = sql.stripLeading().toUpperCase();
        return normalized.startsWith("CREATE INDEX") || normalized.startsWith("CREATE UNIQUE INDEX");
    }

    private void migrateInterviewProcessColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_process", "ai_follow_up_threshold", "INTEGER NOT NULL DEFAULT 70");
        addColumnIfMissing(connection, statement, "interview_process", "ai_min_question_rounds", "INTEGER NOT NULL DEFAULT 5");
        addColumnIfMissing(connection, statement, "interview_process", "ai_max_question_rounds", "INTEGER NOT NULL DEFAULT 10");
        addColumnIfMissing(connection, statement, "interview_process", "anti_cheat_switch_limit", "INTEGER NOT NULL DEFAULT 5");
        addColumnIfMissing(connection, statement, "interview_process", "anti_cheat_switch_count", "INTEGER NOT NULL DEFAULT 0");
        addColumnIfMissing(connection, statement, "interview_process", "ai_output_mode", "VARCHAR(16) NOT NULL DEFAULT 'NORMAL'");
        addColumnIfMissing(connection, statement, "interview_process", "remark", "VARCHAR(2000)");
        addColumnIfMissing(connection, statement, "interview_process", "ai_recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_process", "ai_recording_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_process", "template_id", "INTEGER");
        addColumnIfMissing(connection, statement, "interview_process", "template_name", "VARCHAR(128)");
    }

    private void migrateInterviewProcessTemplateColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_process_template", "version", "INTEGER NOT NULL DEFAULT 0");
    }

    private void migrateInterviewAiRecordColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_ai_record", "process_stage_id", "INTEGER");
        addColumnIfMissing(connection, statement, "interview_ai_record", "stage_scope_id", "INTEGER NOT NULL DEFAULT 0");
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_status", "VARCHAR(32) NOT NULL DEFAULT 'READY'");
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_generation_attempts", "INTEGER NOT NULL DEFAULT 0");
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_generation_token", "VARCHAR(64)");
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_lease_expires_at", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_next_retry_at", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_ai_record", "question_generation_error", "VARCHAR(1000)");
        addColumnIfMissing(connection, statement, "interview_ai_record", "previous_record_id", "INTEGER");
        addColumnIfMissing(connection, statement, "interview_ai_record", "suggested_next_question", "VARCHAR(5000)");
        addColumnIfMissing(connection, statement, "interview_ai_record", "answer_status", "VARCHAR(32) NOT NULL DEFAULT 'PENDING'");
        addColumnIfMissing(connection, statement, "interview_ai_record", "answer_processing_token", "VARCHAR(64)");
        addColumnIfMissing(connection, statement, "interview_ai_record", "answer_lease_expires_at", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_ai_record", "answer_processing_attempts", "INTEGER NOT NULL DEFAULT 0");
        addColumnIfMissing(connection, statement, "interview_ai_record", "answer_error", "VARCHAR(1000)");
        statement.executeUpdate("UPDATE interview_ai_record SET stage_scope_id = COALESCE(process_stage_id, 0)");
        statement.executeUpdate("UPDATE interview_ai_record SET question_status = COALESCE(question_status, 'READY')");
        statement.executeUpdate("UPDATE interview_ai_record SET answer_status = CASE "
                + "WHEN answer_content IS NOT NULL AND average_score IS NOT NULL THEN 'COMPLETED' "
                + "WHEN answer_content IS NOT NULL THEN 'FAILED' ELSE COALESCE(answer_status, 'PENDING') END");
    }

    private void migrateInterviewVideoSessionColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_video_session", "approver_user_id", "INTEGER");
        addColumnIfMissing(connection, statement, "interview_video_session", "approver_name", "VARCHAR(64)");
        addColumnIfMissing(connection, statement, "interview_video_session", "interviewee_join_time", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_video_session", "hr_join_time", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_video_session", "start_time", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_video_session", "end_time", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_video_session", "recording_end_requested_at", dateTimeType());
        addColumnIfMissing(connection, statement, "interview_video_session", "recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_video_session", "hr_recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_video_session", "hr_recording_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_video_session", "interviewee_recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_video_session", "interviewee_recording_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_video_session", "merged_recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_video_session", "merged_recording_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_video_session", "audio_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_video_session", "audio_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_video_session", "transcript_text", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "summary_text", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "summary_status", "VARCHAR(32)");
        widenColumnIfNeeded(statement, "interview_video_session", "summary_status", "VARCHAR(128)");
        addColumnIfMissing(connection, statement, "interview_video_session", "hr_offer_sdp", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "interviewee_answer_sdp", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "hr_ice_candidates", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "interviewee_ice_candidates", "TEXT");
        addColumnIfMissing(connection, statement, "interview_video_session", "recording_file_name", "VARCHAR(255)");
        addColumnIfMissing(connection, statement, "interview_video_session", "process_stage_id", "INTEGER");
    }

    private String dateTimeType() {
        return activeDatabase.type() == DatabaseType.PGSQL ? "TIMESTAMP" : "DATETIME";
    }

    private void migrateRecruitmentCandidateColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "recruitment_candidate", "resume_llm_score", "INTEGER");
        addColumnIfMissing(connection, statement, "recruitment_candidate", "resume_llm_comment", "VARCHAR(2000)");
        addColumnIfMissing(connection, statement, "recruitment_candidate", "resume_llm_status", "VARCHAR(32)");
        addColumnIfMissing(connection, statement, "recruitment_candidate", "resume_llm_evaluated_at", dateTimeType());
    }

    private void migrateRecruitmentJobColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "recruitment_job", "department_id", "INTEGER");
    }

    private void migrateHrEmployeeColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "hr_employee", "source_candidate_id", "INTEGER");
        addColumnIfMissing(connection, statement, "hr_employee", "interview_stage_status", "VARCHAR(64)");
        addColumnIfMissing(connection, statement, "hr_employee", "source_channel", "VARCHAR(64)");
        addColumnIfMissing(connection, statement, "hr_employee", "notes", "VARCHAR(1000)");
    }

    private void migrateReferentialIntegrityConstraints(Connection connection, Statement statement) throws SQLException {
        if (activeDatabase.type() == DatabaseType.SQLITE) {
            // SQLite cannot add foreign-key constraints to existing tables without rebuilding them.
            return;
        }
        ensureForeignKey(connection, statement, "fk_hr_employee_manager", "hr_employee", "manager_employee_id", "hr_employee");
        ensureForeignKey(connection, statement, "fk_hr_department_parent", "hr_department", "parent_department_id", "hr_department");
        ensureForeignKey(connection, statement, "fk_hr_department_manager", "hr_department", "manager_employee_id", "hr_employee");
        ensureEmployeeSourceCandidateForeignKey(connection, statement);
        ensureForeignKey(connection, statement, "fk_binding_employee", "hr_integration_binding", "employee_id", "hr_employee");
        ensureForeignKey(connection, statement, "fk_candidate_interviewee_user", "recruitment_candidate", "interviewee_user_id", "sys_user");
        ensureForeignKey(connection, statement, "fk_process_candidate", "interview_process", "recruitment_candidate_id", "recruitment_candidate");
        ensureForeignKey(connection, statement, "fk_process_interviewee_user", "interview_process", "interviewee_user_id", "sys_user");
        ensureForeignKey(connection, statement, "fk_process_approver_user", "interview_process", "approved_hr_user_id", "sys_user");
        ensureForeignKey(connection, statement, "fk_process_template", "interview_process", "template_id", "interview_process_template");
        ensureForeignKey(connection, statement, "fk_process_stage_process", "interview_process_stage", "process_id", "interview_process");
        ensureForeignKey(connection, statement, "fk_process_stage_approver", "interview_process_stage", "approved_hr_user_id", "sys_user");
        ensureForeignKey(connection, statement, "fk_ai_record_process", "interview_ai_record", "process_id", "interview_process");
        ensureForeignKey(connection, statement, "fk_ai_record_stage", "interview_ai_record", "process_stage_id", "interview_process_stage");
        ensureForeignKey(connection, statement, "fk_video_session_process", "interview_video_session", "process_id", "interview_process");
        ensureForeignKey(connection, statement, "fk_video_session_stage", "interview_video_session", "process_stage_id", "interview_process_stage");
        ensureForeignKey(connection, statement, "fk_video_session_approver", "interview_video_session", "approver_user_id", "sys_user");
    }

    /**
     * The legacy SQLite data set contains a nullable employee source reference which was allowed to
     * outlive its candidate. This is the only historical relationship we repair automatically.
     */
    private void ensureEmployeeSourceCandidateForeignKey(Connection connection, Statement statement) throws SQLException {
        if (activeDatabase.type() != DatabaseType.PGSQL) {
            ensureForeignKey(connection, statement, "fk_hr_employee_source_candidate", "hr_employee",
                    "source_candidate_id", "recruitment_candidate");
            return;
        }

        boolean originalAutoCommit = connection.getAutoCommit();
        int originalIsolation = connection.getTransactionIsolation();
        try {
            connection.setAutoCommit(false);
            connection.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            try (Statement transactionStatement = connection.createStatement()) {
                transactionStatement.executeUpdate("CREATE TABLE IF NOT EXISTS database_migration_orphan_archive ("
                        + "table_name VARCHAR(64) NOT NULL, column_name VARCHAR(64) NOT NULL, "
                        + "child_id INTEGER NOT NULL, invalid_reference_id INTEGER NOT NULL, "
                        + "archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
                transactionStatement.executeUpdate("CREATE INDEX IF NOT EXISTS idx_migration_orphan_archive_expiry "
                        + "ON database_migration_orphan_archive (archived_at)");
                transactionStatement.executeUpdate("DELETE FROM database_migration_orphan_archive "
                        + "WHERE archived_at < CURRENT_TIMESTAMP - INTERVAL '5 days'");

                if (!foreignKeyExists(connection, "hr_employee", "source_candidate_id", "recruitment_candidate")) {
                    transactionStatement.executeUpdate("LOCK TABLE hr_employee, recruitment_candidate "
                            + "IN SHARE ROW EXCLUSIVE MODE");
                    int archivedRows = transactionStatement.executeUpdate("INSERT INTO database_migration_orphan_archive "
                            + "(table_name, column_name, child_id, invalid_reference_id, archived_at) "
                            + "SELECT 'hr_employee', 'source_candidate_id', child.id, child.source_candidate_id, CURRENT_TIMESTAMP "
                            + "FROM hr_employee child LEFT JOIN recruitment_candidate parent "
                            + "ON child.source_candidate_id = parent.id "
                            + "WHERE child.source_candidate_id IS NOT NULL AND parent.id IS NULL");
                    int repairedRows = transactionStatement.executeUpdate("UPDATE hr_employee child SET source_candidate_id = NULL "
                            + "WHERE child.source_candidate_id IS NOT NULL AND NOT EXISTS "
                            + "(SELECT 1 FROM recruitment_candidate parent WHERE parent.id = child.source_candidate_id)");
                    if (archivedRows != repairedRows) {
                        throw new SQLException("Employee source-candidate repair changed while migration was running");
                    }
                    if (repairedRows > 0) {
                        log.warn("Archived and cleared {} orphaned hr_employee.source_candidate_id value(s)", repairedRows);
                    }
                    assertNoOrphanedReferences(transactionStatement, "hr_employee", "source_candidate_id", "recruitment_candidate");
                    execute(transactionStatement, "ALTER TABLE hr_employee ADD CONSTRAINT fk_hr_employee_source_candidate "
                            + "FOREIGN KEY (source_candidate_id) REFERENCES recruitment_candidate(id) ON DELETE RESTRICT");
                }
            }
            connection.commit();
        } catch (SQLException | RuntimeException ex) {
            rollbackEmployeeSourceCandidateMigration(connection, ex);
            throw ex;
        } finally {
            connection.setTransactionIsolation(originalIsolation);
            connection.setAutoCommit(originalAutoCommit);
        }
    }

    private void rollbackEmployeeSourceCandidateMigration(Connection connection, Exception original) {
        try {
            connection.rollback();
        } catch (SQLException rollbackError) {
            original.addSuppressed(rollbackError);
        }
    }

    private void ensureForeignKey(Connection connection, Statement statement, String constraintName, String table,
                                  String column, String referencedTable) throws SQLException {
        if (foreignKeyExists(connection, table, column, referencedTable)) {
            return;
        }
        assertNoOrphanedReferences(statement, table, column, referencedTable);
        execute(statement, "ALTER TABLE " + table + " ADD CONSTRAINT " + constraintName
                + " FOREIGN KEY (" + column + ") REFERENCES " + referencedTable + "(id) ON DELETE RESTRICT");
    }

    private boolean foreignKeyExists(Connection connection, String table, String column, String referencedTable) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet keys = metaData.getImportedKeys(null, null, table)) {
            while (keys.next()) {
                if (column.equalsIgnoreCase(keys.getString("FKCOLUMN_NAME"))
                        && referencedTable.equalsIgnoreCase(keys.getString("PKTABLE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    private void assertNoOrphanedReferences(Statement statement, String table, String column, String referencedTable)
            throws SQLException {
        String sql = "SELECT COUNT(*) FROM " + table + " child LEFT JOIN " + referencedTable
                + " parent ON child." + column + " = parent.id WHERE child." + column + " IS NOT NULL AND parent.id IS NULL";
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            if (resultSet.next() && resultSet.getLong(1) > 0) {
                throw new IllegalStateException("Cannot enforce foreign key " + table + "." + column
                        + " because orphaned references exist. Resolve them before deployment.");
            }
        }
    }

    private void addColumnIfMissing(Connection connection, Statement statement, String table, String column, String definition) throws SQLException {
        if (columnExists(connection, table, column)) {
            return;
        }
        execute(statement, "ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
        log.info("Added migration column {}.{}", table, column);
    }

    private boolean columnExists(Connection connection, String table, String column) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet columns = metaData.getColumns(null, null, table, column)) {
            if (columns.next()) {
                return true;
            }
        }
        try (ResultSet columns = metaData.getColumns(null, null, table.toUpperCase(), column.toUpperCase())) {
            return columns.next();
        }
    }

    private void migrateSysUserColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "sys_user", "must_change_password", "INTEGER NOT NULL DEFAULT 0");
        addColumnIfMissing(connection, statement, "sys_user", "mobile_phone_normalized", "VARCHAR(32)");
        addColumnIfMissing(connection, statement, "sys_user", "email_normalized", "VARCHAR(128)");
        statement.executeUpdate("UPDATE sys_user SET mobile_phone_normalized = "
                + "CASE WHEN mobile_phone IS NULL OR TRIM(mobile_phone) = '' THEN NULL ELSE TRIM(mobile_phone) END");
        statement.executeUpdate("UPDATE sys_user SET email_normalized = "
                + "CASE WHEN email IS NULL OR TRIM(email) = '' THEN NULL ELSE LOWER(TRIM(email)) END");
        assertNoDuplicateNormalizedContacts(statement, "mobile_phone_normalized", "mobile phone");
        assertNoDuplicateNormalizedContacts(statement, "email_normalized", "email");
    }

    private void assertNoDuplicateNormalizedContacts(Statement statement, String column, String label) throws SQLException {
        String sql = "SELECT COUNT(*) FROM (SELECT " + column + " FROM sys_user WHERE " + column
                + " IS NOT NULL GROUP BY " + column + " HAVING COUNT(*) > 1) duplicate_contacts";
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            if (resultSet.next() && resultSet.getLong(1) > 0) {
                throw new IllegalStateException("Cannot add global " + label
                        + " uniqueness while duplicate normalized sys_user contacts exist. Resolve duplicates before deployment.");
            }
        }
    }

    private void assertNoDuplicateBusinessKeys(Statement statement) throws SQLException {
        assertNoDuplicateBusinessKey(statement, "recruitment_candidate", "job_id, interviewee_user_id",
                "interviewee_user_id IS NOT NULL", "candidate applications for one job and interviewee");
        assertNoDuplicateBusinessKey(statement, "interview_process", "recruitment_candidate_id",
                "recruitment_candidate_id IS NOT NULL", "interview processes for one candidate");
        assertNoDuplicateBusinessKey(statement, "hr_employee", "source_candidate_id",
                "source_candidate_id IS NOT NULL", "employees generated from one candidate");
        assertNoDuplicateBusinessKey(statement, "interview_ai_record", "process_id, stage_scope_id, sequence_no",
                "sequence_no IS NOT NULL", "AI questions with one process stage and sequence number");
    }

    private void assertNoDuplicateBusinessKey(Statement statement, String table, String columns,
                                              String predicate, String label) throws SQLException {
        String sql = "SELECT COUNT(*) FROM (SELECT " + columns + " FROM " + table
                + " WHERE " + predicate + " GROUP BY " + columns + " HAVING COUNT(*) > 1) duplicate_rows";
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            if (resultSet.next() && resultSet.getLong(1) > 0) {
                throw new IllegalStateException("Cannot enforce uniqueness for " + label
                        + " while duplicate rows exist. Resolve duplicates before deployment.");
            }
        }
    }

    private void migrateInterviewProcessStageColumns(Connection connection, Statement statement) throws SQLException {
        addColumnIfMissing(connection, statement, "interview_process_stage", "ai_recording_path", "VARCHAR(500)");
        addColumnIfMissing(connection, statement, "interview_process_stage", "ai_recording_file_name", "VARCHAR(255)");
    }

    private void migrateDatabaseGeneratedPrimaryKeys(Connection connection, Statement statement) throws SQLException {
        switch (activeDatabase.type()) {
            case SQLITE -> {
                // INTEGER PRIMARY KEY is already SQLite's row-id backed generated key.
            }
            case MYSQL -> migrateMySqlPrimaryKeys(connection, statement);
            case PGSQL -> migratePostgreSqlPrimaryKeys(connection, statement);
        }
    }

    private void migrateMySqlPrimaryKeys(Connection connection, Statement statement) throws SQLException {
        for (String table : PRIMARY_KEY_TABLES) {
            if (!isAutoIncrement(connection, table)) {
                statement.executeUpdate("ALTER TABLE " + table + " MODIFY COLUMN id INTEGER NOT NULL AUTO_INCREMENT");
                log.info("Enabled AUTO_INCREMENT for {}.id", table);
            }
            statement.executeUpdate("ALTER TABLE " + table + " AUTO_INCREMENT = " + nextPrimaryKeyValue(connection, table));
        }
    }

    private void migratePostgreSqlPrimaryKeys(Connection connection, Statement statement) throws SQLException {
        for (String table : PRIMARY_KEY_TABLES) {
            if (!hasPostgreSqlPrimaryKeyGenerator(connection, table)) {
                statement.executeUpdate("ALTER TABLE " + table + " ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
                log.info("Enabled identity generation for {}.id", table);
            }
            alignPostgreSqlSequence(connection, table);
        }
    }

    private boolean isAutoIncrement(Connection connection, String table) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet columns = metaData.getColumns(null, null, table, "id")) {
            return columns.next() && "YES".equalsIgnoreCase(columns.getString("IS_AUTOINCREMENT"));
        }
    }

    private boolean hasPostgreSqlPrimaryKeyGenerator(Connection connection, String table) throws SQLException {
        String sql = "SELECT is_identity, column_default FROM information_schema.columns "
                + "WHERE table_schema = current_schema() AND table_name = ? AND column_name = 'id'";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, table);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next()) {
                    throw new SQLException("Missing primary key column " + table + ".id");
                }
                String defaultValue = resultSet.getString("column_default");
                return "YES".equalsIgnoreCase(resultSet.getString("is_identity"))
                        || (defaultValue != null && defaultValue.toLowerCase().startsWith("nextval("));
            }
        }
    }

    private void alignPostgreSqlSequence(Connection connection, String table) throws SQLException {
        String sequenceName;
        try (PreparedStatement statement = connection.prepareStatement("SELECT pg_get_serial_sequence(?, 'id')")) {
            statement.setString(1, table);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next() || resultSet.getString(1) == null) {
                    throw new SQLException("Missing generated-key sequence for " + table + ".id");
                }
                sequenceName = resultSet.getString(1);
            }
        }
        long maximumId = maximumPrimaryKeyValue(connection, table);
        try (PreparedStatement statement = connection.prepareStatement("SELECT setval(CAST(? AS regclass), ?, ?)")) {
            statement.setString(1, sequenceName);
            statement.setLong(2, Math.max(maximumId, 1));
            statement.setBoolean(3, maximumId > 0);
            statement.execute();
        }
    }

    private long nextPrimaryKeyValue(Connection connection, String table) throws SQLException {
        long maximumId = maximumPrimaryKeyValue(connection, table);
        return maximumId == Long.MAX_VALUE ? Long.MAX_VALUE : Math.max(maximumId + 1, 1);
    }

    private long maximumPrimaryKeyValue(Connection connection, String table) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery("SELECT COALESCE(MAX(id), 0) FROM " + table)) {
            return resultSet.next() ? resultSet.getLong(1) : 0;
        }
    }

    private void widenColumnIfNeeded(Statement statement, String table, String column, String definition) throws SQLException {
        if (activeDatabase.type() != DatabaseType.PGSQL) {
            return;
        }
        statement.executeUpdate("ALTER TABLE " + table + " ALTER COLUMN " + column + " TYPE " + definition);
    }

    private boolean messageContains(SQLException ex, String value) {
        return ex.getMessage() != null && ex.getMessage().contains(value);
    }

    private String firstLine(String sql) {
        int index = sql.indexOf('\n');
        return index >= 0 ? sql.substring(0, index) : sql;
    }
}
