spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autohr
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    com.autohr: info
