spring:
  datasource:
    url: jdbc:sqlite:autohr-test.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.autohr: debug
